name: Coverage

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.8
            use_jax: "YES"
          - os: ubuntu-latest
            python-version: 3.8
            use_jax: "NO"
          - os: macos-latest
            python-version: 3.8
            use_jax: "YES"

        #python-version: [3.6, 3.7, 3.8]
        #os: [ubuntu-latest, macos-latest]

    env:
      MPICH_INTERFACE_HOSTNAME: localhost
      USE_JAX: ${{ matrix.use_jax }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install MPI
        run: |
          sh ./conf/travis-install-mpi.sh mpich

      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-jax_${{ matrix.use_jax }}-pip-${{ hashFiles('**/setup.py', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Pip install python dependencies
        run: |
          echo "Jax variable is: ${{ matrix.use_jax }}"
          if [ ! ${{ matrix.use_jax }} == "NO" ]; then
            echo "Installing jax & co"
            python -m pip install jax jaxlib mpi4jax flax
          fi
          pip install -e ".[dev,mpi]"

      - name: MPI tests
        run: |
          mpirun -host localhost:2 -np 2 coverage run -m pytest -n 0 Test/MPI

      - name: Netket tests
        run : pytest --cov=netket --cov-append

      - name: Upload coverage
        uses: codecov/codecov-action@v1
